# Site
name: 'SQlatino'
description: 'Data Science knowledge in spanish and english'
logo: 'assets/images/logo.png'
favicon: 'assets/images/log.png'
baseurl: 
disqus: 'demowebsite'
email: ' '
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Cesar
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Cesar P the founder of SQlatino "
      email:          
      twitter:        

    jane:
      name:           Jane
      site:           
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          
      twitter:        

    sah:
      name:           Sal
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of some SQL and Python articles"
      email:          
      twitter:        

    Vanesa:
      name:           Vanesa
      site:           
      avatar:         /assets/images/avatar2.jpg
      bio:            "Managing, Accounting and Spanish Translator"
      email:          fakemail@gmail.com
      twitter:             


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
